name: inventory
version: 1.0.1
main: inventoryPlugin.Main
description: inventory plugin

commands:
  changename:
    description: changename
    usage: changename + "name"
  inv:
    description: inventory
  spawnset:
    description: set spawn